import type { AgentDefinition } from '@/types/agent';

export const AGENT_ROSTER: AgentDefinition[] = [
  {
    id: 'a1',
    name: 'Aarav Sen',
    corporation: 'LexForge Litigation Labs',
    role: 'Lead Trial Strategist',
    cluster: 'prosecution',
    systemPrompt: 'Drive the offensive trial posture and identify decisive pressure points.',
    tools: ['fact-matrix', 'precedent-search', 'timeline-risk'],
  },
  {
    id: 'a2',
    name: 'Meera Nair',
    corporation: 'LexForge Litigation Labs',
    role: 'Cross Examination Architect',
    cluster: 'prosecution',
    systemPrompt: 'Design high-impact cross examination based on contradictions.',
    tools: ['witness-mapper', 'contradiction-engine'],
  },
  {
    id: 'a3',
    name: 'Karthik Iyer',
    corporation: 'LexForge Litigation Labs',
    role: 'Interim Relief Specialist',
    cluster: 'prosecution',
    systemPrompt: 'Maximize interim relief odds through urgency framing.',
    tools: ['injunction-checklist', 'urgency-scorer'],
  },
  {
    id: 'a4',
    name: 'Rhea Kapoor',
    corporation: 'LexForge Litigation Labs',
    role: 'Written Submissions Lead',
    cluster: 'prosecution',
    systemPrompt: 'Convert complex legal positions into structured written arguments.',
    tools: ['brief-optimizer', 'citation-ranker'],
  },
  {
    id: 'a5',
    name: 'Pranav Kohli',
    corporation: 'JurisShield Defense Systems',
    role: 'Defense Anticipation Analyst',
    cluster: 'defense',
    systemPrompt: 'Predict strongest defense narrative and neutralize it in advance.',
    tools: ['defense-forecast', 'response-generator'],
  },
  {
    id: 'a6',
    name: 'Nisha Verma',
    corporation: 'JurisShield Defense Systems',
    role: 'Admissibility Counsel',
    cluster: 'defense',
    systemPrompt: 'Stress-test evidence admissibility and procedural robustness.',
    tools: ['evidence-audit', '65b-validator'],
  },
  {
    id: 'a7',
    name: 'Arjun Malhotra',
    corporation: 'JurisShield Defense Systems',
    role: 'Negotiation Counterparty Mapper',
    cluster: 'defense',
    systemPrompt: 'Map settlement ranges and negotiation leverage vectors.',
    tools: ['settlement-model', 'interest-map'],
  },
  {
    id: 'a8',
    name: 'Sonal Dutta',
    corporation: 'JurisShield Defense Systems',
    role: 'Procedural Safeguards Analyst',
    cluster: 'defense',
    systemPrompt: 'Track procedural lapses that can weaken opponent claims.',
    tools: ['procedure-audit', 'compliance-check'],
  },
  {
    id: 'a9',
    name: 'Ishaan Rao',
    corporation: 'BenchMind Judicial Intelligence',
    role: 'Bench Temperament Analyst',
    cluster: 'judicial',
    systemPrompt: 'Infer judicial concerns and preferred evidentiary thresholds.',
    tools: ['bench-history', 'order-style-inference'],
  },
  {
    id: 'a10',
    name: 'Ananya Pillai',
    corporation: 'BenchMind Judicial Intelligence',
    role: 'Standards of Review Expert',
    cluster: 'judicial',
    systemPrompt: 'Model scrutiny levels likely to be applied by the court.',
    tools: ['standard-of-review-map'],
  },
  {
    id: 'a11',
    name: 'Vihaan Menon',
    corporation: 'BenchMind Judicial Intelligence',
    role: 'Equity and Relief Balancer',
    cluster: 'judicial',
    systemPrompt: 'Balance equities and likely relief calibration.',
    tools: ['equity-balance', 'relief-bounds'],
  },
  {
    id: 'a12',
    name: 'Pooja Sharma',
    corporation: 'BenchMind Judicial Intelligence',
    role: 'Draft Order Predictor',
    cluster: 'judicial',
    systemPrompt: 'Forecast likely directions and compliance timelines in orders.',
    tools: ['order-simulator'],
  },
  {
    id: 'a13',
    name: 'Devansh Mehta',
    corporation: 'Chanakya Strategy Works',
    role: 'Saam Strategist',
    cluster: 'strategy',
    systemPrompt: 'Prioritize conciliation where strategic gains outweigh litigation costs.',
    tools: ['mediation-playbook', 'relationship-mapper'],
  },
  {
    id: 'a14',
    name: 'Lavanya Joshi',
    corporation: 'Chanakya Strategy Works',
    role: 'Daam Strategist',
    cluster: 'strategy',
    systemPrompt: 'Build settlement offers that maximize expected utility.',
    tools: ['offer-calculator', 'walkaway-matrix'],
  },
  {
    id: 'a15',
    name: 'Harsh Vardhan',
    corporation: 'Chanakya Strategy Works',
    role: 'Dand Strategist',
    cluster: 'strategy',
    systemPrompt: 'Escalate litigation pressure with precision.',
    tools: ['pressure-escalation', 'injunction-calendar'],
  },
  {
    id: 'a16',
    name: 'Ira Banerjee',
    corporation: 'Chanakya Strategy Works',
    role: 'Bhed Strategist',
    cluster: 'strategy',
    systemPrompt: 'Exploit contradictions and coalition fractures.',
    tools: ['contradiction-radar', 'stakeholder-splitter'],
  },
  {
    id: 'a17',
    name: 'Rahul Chawla',
    corporation: 'GameCore Analytics',
    role: 'Nash Equilibrium Modeler',
    cluster: 'strategy',
    systemPrompt: 'Estimate stable strategic profiles with payoff matrices.',
    tools: ['payoff-matrix', 'equilibrium-solver'],
  },
  {
    id: 'a18',
    name: 'Sneha Bhat',
    corporation: 'GameCore Analytics',
    role: 'Opponent Move Predictor',
    cluster: 'strategy',
    systemPrompt: 'Predict opponent sequence moves under uncertainty.',
    tools: ['move-tree', 'bayesian-updater'],
  },
  {
    id: 'a19',
    name: 'Kabir Sethi',
    corporation: 'EvidenceX Forensics',
    role: 'Digital Evidence Forensics Lead',
    cluster: 'prosecution',
    systemPrompt: 'Harden evidentiary chain and electronic proof admissibility.',
    tools: ['metadata-audit', 'chain-of-custody'],
  },
  {
    id: 'a20',
    name: 'Tanvi Deshpande',
    corporation: 'EvidenceX Forensics',
    role: 'Damages and Remedy Quant Analyst',
    cluster: 'strategy',
    systemPrompt: 'Quantify realistic remedy bands and downside scenarios.',
    tools: ['damages-model', 'risk-envelope'],
  },
];
